# Generated by Django 6.0.2 on 2026-02-25 07:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TRIPOD', 'Tripod'), ('GIMBAL', 'Gimbal'), ('MIC', 'Microphone'), ('LIGHT', 'Lighting Kit'), ('BATTERY', 'Battery'), ('BAG', 'Camera Bag')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='accessory_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_model', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('CANON', 'Canon'), ('SONY', 'Sony'), ('NIKON', 'Nikon'), ('PANASONIC', 'Panasonic'), ('FUJIFILM', 'Fujifilm')], max_length=50)),
                ('camera_type', models.CharField(choices=[('DSLR', 'DSLR'), ('MIRRORLESS', 'Mirrorless'), ('CINEMA', 'Cinema Camera'), ('ACTION', 'Action Camera')], max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('sensor', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='camera_images/')),
                ('document', models.FileField(upload_to='camera_docs/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_name', models.CharField(max_length=100)),
                ('lens_type', models.CharField(choices=[('PRIME', 'Prime'), ('ZOOM', 'Zoom'), ('WIDE', 'Wide Angle'), ('TELE', 'Telephoto'), ('MACRO', 'Macro')], max_length=50)),
                ('mount_type', models.CharField(max_length=50)),
                ('focal_length', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='lens_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_seller', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.FileField(upload_to='documents/')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('customer_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.accessory')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.camera')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.customer')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.lens')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.accessory')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.camera')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.customer')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.lens')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_proof', models.FileField(upload_to='documents/')),
                ('seller_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lens',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.seller'),
        ),
        migrations.AddField(
            model_name='camera',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.seller'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.seller'),
        ),
    ]
