# Generated by Django 6.0.2 on 2026-02-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
    ]
