# Generated by Django 6.0.2 on 2026-02-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TRIPOD', 'Tripod'), ('GIMBAL', 'Gimbal'), ('MIC', 'Microphone'), ('LIGHT', 'Lighting Kit'), ('BATTERY', 'Battery'), ('BAG', 'Camera Bag')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='accessory_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_model', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('CANON', 'Canon'), ('SONY', 'Sony'), ('NIKON', 'Nikon'), ('PANASONIC', 'Panasonic'), ('FUJIFILM', 'Fujifilm')], max_length=50)),
                ('camera_type', models.CharField(choices=[('DSLR', 'DSLR'), ('MIRRORLESS', 'Mirrorless'), ('CINEMA', 'Cinema Camera'), ('ACTION', 'Action Camera')], max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('sensor', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='camera_images/')),
                ('document', models.FileField(upload_to='camera_docs/')),
                ('is_available', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_name', models.CharField(max_length=100)),
                ('lens_type', models.CharField(choices=[('PRIME', 'Prime'), ('ZOOM', 'Zoom'), ('WIDE', 'Wide Angle'), ('TELE', 'Telephoto'), ('MACRO', 'Macro')], max_length=50)),
                ('mount_type', models.CharField(max_length=50)),
                ('focal_length', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='lens_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.seller')),
            ],
        ),
    ]
