# Generated by Django 6.0.2 on 2026-02-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0002_alter_accessory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='seller',
        ),
        migrations.AddField(
            model_name='camera',
            name='camara_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cam_borrow.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(default=1, upload_to='accessory_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.camera'),
            preserve_default=False,
        ),
    ]
