# Generated by Django 6.0.2 on 2026-02-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0003_remove_camera_seller_camera_camara_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.camera'),
        ),
    ]
