# Generated by Django 6.0.2 on 2026-02-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0004_alter_cart_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.camera'),
            preserve_default=False,
        ),
    ]
