# Generated by Django 6.0.2 on 2026-02-28 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0005_alter_cart_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam_borrow.camera'),
        ),
    ]
