# Generated by Django 6.0.2 on 2026-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0006_alter_cart_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='camera',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lens',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
