# Generated by Django 6.0.2 on 2026-03-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_borrow', '0007_accessory_stock_camera_stock_lens_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
